### PR TITLE
repo: fix expiration for all roles

### LINKED ISSUE #103: TUF expiry contains microseconds
From TUF specification:

> The expected format of the combined date and time string is "YYYY-MM-DDTHH:MM:SSZ". Time is always in UTC, and the "Z" time zone designator is attached to indicate a zero UTC offset. An example date-time string is "1985-10-21T01:21:00Z".

To me this says that the expiry string should not contain microseconds. Current sigstore metadata contains microseconds: https://github.com/sigstore/root-signing/blob/main/repository/repository/2.root.json#L27

I'm not sure if defining expiry this strictly in the spec is useful but the definition seems clear and in python-tuf we currently implement the spec strictly so fail to deserialize this metadata. 

The related python-tuf issue (we'll have to decide if we should support msecs or not): https://github.com/theupdateframework/python-tuf/issues/1858

### LINKED ISSUE #267: Correct the generation of expirations for metadata
**Description**

**Version**

the snapshot was generated with the wrong expiration) (Generate expiration as Now + 2/3 weeks)

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Ticket Link

Fixes https://github.com/sigstore/root-signing/issues/267
Fixes https://github.com/sigstore/root-signing/issues/103

#### Release Note

```release-note

```

### CODE REVIEW

File: cmd/tuf/app/init.go [hunk 1]
```diff
@@ -20,8 +20,27 @@ import (
...
+// Threshold for root and targets signers.
 var DefaultThreshold = 3
 
+// Time to role expiration represented as a list of ints corresponding to
+// (years, months, days).
+var RoleExpiration = map[string][]int{
+	"root":      {0, 6, 0},
+	"targets":   {0, 6, 0},
+	"snapshot":  {0, 0, 21},
+	"timestamp": {0, 6, 14},
```
Comment (Hayden-IO) [inline cmd/tuf/app/init.go]: {0, 0, 14}

File: cmd/tuf/app/init.go [hunk 2]
```diff
@@ -20,8 +20,27 @@ import (
...
+}
+
+func getExpiration(role string) time.Time {
+	// Default expiration is for targets.
```
Comment (Hayden-IO) [inline cmd/tuf/app/init.go]: Should we print a warning if we don't find a role? Just worried this might cause a subtle issue in the future around adding extra roles

Comment (asraa) [reply cmd/tuf/app/init.go]: Extra roles would always be "targets" roles though, correct? (for delegations)

Unless explicitly requiring a different expiration.

Comment (Hayden-IO) [reply cmd/tuf/app/init.go]: Or maybe this is intentional, since it's for delegates?

Comment (asraa) [reply cmd/tuf/app/init.go]: Actually, +1 on printing the warning, I think it's good to have verbosity when there's choice involved.

Comment (asraa) [reply cmd/tuf/app/init.go]: Yeah, that was the thought! I can add that comment about delegations since it was unclear

File: cmd/tuf/app/init.go [hunk 3]
```diff
@@ -20,8 +20,29 @@ import (
...
+	"timestamp": {0, 0, 14},
+}
+
+func getExpiration(role string) time.Time {
+	// Default expiration for any delegated role is the targets expiration.
+	times, ok := RoleExpiration[role]
+	if !ok {
+		times = RoleExpiration["targets"]
+		fmt.Fprintf(os.Stderr, "Explicit expiration not found, using default targets expiration in %d years, %d months, %d days\n",
+			times[9], times[1], times[2])
```
Comment (Hayden-IO) [inline cmd/tuf/app/init.go]: `times[0]`

**Review by Hayden-IO — DISMISSED** [review]

**Review by Hayden-IO — APPROVED** [review]

**Review by dlorenc — APPROVED** [review]
