### PR TITLE
fix: properly update snapshot and timestamp keys

### LINKED ISSUE #293: feat: support snapshot/timestamp key updates
**Description**

Right now we won't revoke old keys if we update to a new snapshot or timestamp key.

**Version**

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Fixes https://github.com/sigstore/root-signing/issues/293

* fix: Properly handles updates for snapshot and timestamp keys

Previously, we would `AddVerificationKey` for any specified snapshot/timestamp key but we would NOT revoke any old ones. This revokes any old ones. This is important for v5 so when we re-interpret keys as PEM, we properly revoke the old hex keys.

### CODE REVIEW

File: pkg/repo/repo.go [hunk 1]
```diff
@@ -272,3 +273,33 @@ func GetSigningKeyIDsForRole(name string, store tuf.LocalStore) (
 	}
 	return res, fmt.Errorf("role %s not found", name)
 }
+
+// UpdateRoleKeys updates the roles keys, and handles the logic for
+// revoking any old keys.
+func UpdateRoleKeys(repo *tuf.Repo, store tuf.LocalStore, role string, keys []*data.PublicKey,
```
Comment (kommendorkapten) [inline pkg/repo/repo.go:279]: Nice refactor by removing this code from `InitCmd`!

File: tests/e2e_test.go [hunk 2]
```diff
@@ -1054,7 +1054,7 @@ func TestEcdsaHexToPEMMigration(t *testing.T) {
 		t.Fatal(err)
 	}
 	for _, roleName := range []string{"root", "targets"} {
-		role, ok := root.Roles["root"]
+		role, ok := root.Roles[roleName]
```
Comment (kommendorkapten) [inline tests/e2e_test.go:762]: Good catch!

File: tests/e2e_test.go [hunk 3]
```diff
@@ -1127,3 +1166,111 @@ func TestEcdsaHexToPEMMigration(t *testing.T) {
...
+	if err := os.WriteFile(testTarget, []byte("abc"), 0600); err != nil {
+		t.Fatal(err)
+	}
+
+	rootSerial, err := CreateTestHsmSigner(td, rootCA, rootSigner)
+	if err != nil {
+		t.Fatal(err)
+	}
+	snapshotKey1 := createTestSigner(t)
+	timestampKey := createTestSigner(t)
```
Comment (kommendorkapten) [inline tests/e2e_test.go]: Seen very similar code a lot now, would it make sense to create a method for prepare such a test fixture? Where eg a list of "names" are provided and a test signer is created for each of them, list of target files etc.

**Review by kommendorkapten — DISMISSED** [review]
LGTM

File: tests/e2e_test.go (hunk 3 above)
Comment (asraa) [reply tests/e2e_test.go]: thanks! yes! updated to use a repo test stack: it can be improved a little, but it's a start

**Review by joshuagl — APPROVED** [review]
This is great, the refactored code is much easier to follow and much better tested 🎉

**Review by Hayden-IO — APPROVED** [review]

**Comment by dlorenc** [comment]
LGTM!

**Review by cdris — APPROVED** [review]
