### PR TITLE
test: add regression test to ensure snapshotting fails if root/targets invalid

### LINKED ISSUE #238: Verify root/targets before snapshotting. (Remove placeholder signatures)
**Description**

This caused a failure in root v3 -- empty sigs will return an invalid signature: [https://github.com/theupdateframework/go-tuf/blob/ed6788e710fc3093a7ecc2d078bf734c0f200d8d/verify/verify.go#L107](https://www.google.com/url?q=https://github.com/theupdateframework/go-tuf/blob/ed6788e710fc3093a7ecc2d078bf734c0f200d8d/verify/verify.go%23L107&sa=D&source=docs&ust=1652807861709162&usg=AOvVaw08aTDCf7CQtPml9OaajwBX)

It is interesting that `Snapshot` doesn't fail if the root/targets are invalid. This would be a nice feature to add to go-tuf for resilience. If that's out of scope for the repo manager, we should verify the metadata files here.

### PR DESCRIPTION
**Pull request by asraa**
Fixes https://github.com/sigstore/root-signing/issues/238

This is fixed upstream in go-tuf: we will now fail in `SnapshotCmd` if the root and/or targets are invalid (not signed).

Signed-off-by: Asra Ali <asraa@google.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Review by dlorenc — DISMISSED** [review]

File: tests/e2e_test.go [hunk 1]
```diff
@@ -188,3 +188,57 @@ func TestSignRootTargets(t *testing.T) {
...
+	snapshotKey := createTestSigner(t)
+	timestampKey := createTestSigner(t)
+
+	// Initialize succeeds.
+	if err := app.InitCmd(ctx, td, "", 1, targetsConfig, snapshotKey, timestampKey); err != nil {
+		t.Fatal(err)
+	}
+
+	// Validate that root and targets have one unfilled signature.
+	// TODO: When #281 is merged, add a test with a valid threshold achieved
```
Comment (joshuagl) [inline tests/e2e_test.go]: #281 in this repo is a merged PR.

**Review by joshuagl — DISMISSED** [review]
LGTM. Minor nit on a code comment.

File: tests/e2e_test.go (hunk 1 above)
Comment (asraa) [reply tests/e2e_test.go]: yep! it was merged concurrently -- working on resolving that TODO now :)

Comment (asraa) [reply tests/e2e_test.go]: done now -- added more to that test so that after signing with 1/1 threshold sigs, Snapshotting succeeds because we extraneous placeholder are cleared

**Review by dlorenc — APPROVED** [review]

**Review by joshuagl — APPROVED** [review]
